export { default as Fullscreen } from './Fullscreen'
export { default as InstagramPost } from './InstagramPost'
export { default as Letter } from './Letter'
export { default as SocialStory } from './SocialStory'
export { default as Tabloid } from './Tabloid'
export { default as Tweet } from './Tweet'
export { default as Widescreen } from './Widescreen'
